version: '3.8'  # Use the latest Compose file format

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - EXTERNAL_IP_MEASUREMENT_URL=https://api.ipify.org?format=json
      - IPHUB_API_KEY=MjQ0NTc6emRmVGF5dzltN0pqRFp6a0NqcHF5alVwOFVVMDcxY1U= # Get API key from environment
    depends_on:  # Optional, but good practice for Nginx
      - nginx

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt  # For Let's Encrypt certificates (if using)
