version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - EXTERNAL_IP_MEASUREMENT_URL=https://api.ipify.org?format=json

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - web